modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "${issue_tracker}"

[[mods]]
modId = "${mod_id}"
version = "${project_version}"
displayName = "${mod_name}"
displayURL = "${display_url}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${mc_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "jei"
    type = "optional"
    versionRange = "${jei_version_range}"
    ordering = "AFTER"
    side = "CLIENT"

[[dependencies.${mod_id}]]
    modId = "crafttweaker"
    type = "optional"
    versionRange = "${crafttweaker_version_range}"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "tconstruct"
    type = "optional"
    versionRange = "${tconstruct_version_range}"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "jade"
    type = "optional"
    versionRange = "${jade_version_range}"
    ordering = "AFTER"
    side = "BOTH"
